version: '2.4'

services: 
  storage:
    image: elasticsearch:7.10.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
    mem_limit: "4096M"
  zipkin:
    image: openzipkin/zipkin:3
    container_name: "zipkin"
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: elasticsearch:9200
    ports: 
      - "9411:9411/tcp"
    mem_limit: "4096M"
    depends_on:
     - storage
  logstash:
    image: "library/logstash:7.10.1"
    volumes:
      - ./config/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "9600:9600"
      - "5000:5000"
    mem_limit: "4096M"
  kibana:
    image: "kibana:7.10.1"
    volumes:
      - ./config/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - storage
    mem_limit: "4096M"