management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_HOST:http://localhost:9411/api/v2/spans}
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        greeting: true
        http:
          server:
            requests: true
eureka:
  client:
    service-url:
      defaultZone: ${REGISTER_CENTER:http://localhost:12331/eureka/}
debug: false